"""Disease -> specialist mapping for AI_HealthMate.
Keys match the disease labels supplied for the current 702-disease model.
This is a specialist-routing aid, not a diagnosis.
"""

DISEASE_SPECIALIST = {
    'Rare Disease': 'General Physician',
    'abdominal aortic aneurysm': 'Cardiologist',
    'abdominal hernia': 'General Surgeon',
    'abscess of nose': 'ENT Specialist',
    'abscess of the lung': 'Pulmonologist',
    'abscess of the pharynx': 'General Surgeon',
    'acanthosis nigricans': 'Dermatologist',
    'acariasis': 'General Physician',
    'achalasia': 'General Physician',
    'acne': 'Dermatologist',
    'actinic keratosis': 'Dermatologist',
    'acute bronchiolitis': 'Pulmonologist',
    'acute bronchitis': 'Pulmonologist',
    'acute bronchospasm': 'Pulmonologist',
    'acute fatty liver of pregnancy (aflp)': 'Gynecologist / Obstetrician',
    'acute glaucoma': 'Ophthalmologist',
    'acute kidney injury': 'Nephrologist',
    'acute otitis media': 'ENT Specialist',
    'acute pancreatitis': 'Gastroenterologist',
    'acute respiratory distress syndrome (ards)': 'General Physician',
    'acute sinusitis': 'ENT Specialist',
    'acute stress reaction': 'General Physician',
    'adhesive capsulitis of the shoulder': 'Orthopedic Specialist',
    'adjustment reaction': 'General Physician',
    'adrenal adenoma': 'Endocrinologist',
    'alcohol abuse': 'Psychiatrist',
    'alcohol intoxication': 'General Physician',
    'alcohol withdrawal': 'Psychiatrist',
    'alcoholic liver disease': 'Gastroenterologist',
    'allergy': 'Allergist / Immunologist',
    'allergy to animals': 'Neurologist',
    'alopecia': 'Dermatologist',
    'alzheimer disease': 'Neurologist',
    'amblyopia': 'Ophthalmologist',
    'amyotrophic lateral sclerosis (als)': 'Neurologist',
    'anal fissure': 'Gastroenterologist',
    'anal fistula': 'Gastroenterologist',
    'anemia': 'Hematologist',
    'anemia due to chronic kidney disease': 'Nephrologist',
    'anemia due to malignancy': 'Hematologist',
    'anemia of chronic disease': 'Hematologist',
    'angina': 'Cardiologist',
    'ankylosing spondylitis': 'Orthopedic Specialist',
    'anxiety': 'Psychiatrist',
    'aortic valve disease': 'Cardiologist',
    'aphakia': 'Ophthalmologist',
    'aphthous ulcer': 'Dentist / Oral & Maxillofacial Specialist',
    'aplastic anemia': 'Hematologist',
    'appendicitis': 'General Surgeon',
    'arrhythmia': 'Cardiologist',
    'arthritis of the hip': 'Orthopedic Specialist',
    'ascending cholangitis': 'Gastroenterologist',
    'asperger syndrome': 'Psychiatrist',
    'asthma': 'Pulmonologist',
    'astigmatism': 'Ophthalmologist',
    'atelectasis': 'General Physician',
    "athlete's foot": 'Dermatologist',
    'atonic bladder': 'Urologist',
    'atrial fibrillation': 'Cardiologist',
    'atrial flutter': 'Cardiologist',
    'atrophic skin condition': 'Dermatologist',
    'atrophic vaginitis': 'Gynecologist / Obstetrician',
    'atrophy of the corpus cavernosum': 'General Physician',
    'attention deficit hyperactivity disorder (adhd)': 'Psychiatrist',
    'autism': 'Psychiatrist',
    'autonomic nervous system disorder': 'General Physician',
    'avascular necrosis': 'Orthopedic Specialist',
    'balanitis': 'Urologist',
    'bell palsy': 'Neurologist',
    'benign kidney cyst': 'General Physician',
    'benign paroxysmal positional vertical (bppv)': 'General Physician',
    'benign prostatic hyperplasia (bph)': 'General Physician',
    'benign vaginal discharge (leukorrhea)': 'Gynecologist / Obstetrician',
    'bipolar disorder': 'Psychiatrist',
    'birth trauma': 'General Physician',
    'bladder cancer': 'Oncologist',
    'bladder disorder': 'Urologist',
    'bladder obstruction': 'Urologist',
    'blepharitis': 'Ophthalmologist',
    'blepharospasm': 'Ophthalmologist',
    'bone cancer': 'Oncologist',
    'bone disorder': 'Orthopedic Specialist',
    'bone spur of the calcaneous': 'Orthopedic Specialist',
    'brachial neuritis': 'Neurologist',
    'brain cancer': 'Oncologist',
    'breast cancer': 'Oncologist',
    'breast cyst': 'Gynecologist / Obstetrician',
    'breast infection (mastitis)': 'Gynecologist / Obstetrician',
    'broken tooth': 'Dentist / Oral & Maxillofacial Specialist',
    'bunion': 'Orthopedic Specialist',
    'burn': 'Dermatologist',
    'bursitis': 'Orthopedic Specialist',
    'callus': 'Dermatologist',
    'carbon monoxide poisoning': 'General Physician',
    'cardiac arrest': 'Cardiologist',
    'cardiomyopathy': 'Cardiologist',
    'carpal tunnel syndrome': 'Orthopedic Specialist',
    'cataract': 'Ophthalmologist',
    'celiac disease': 'General Physician',
    'cellulitis or abscess of mouth': 'Dermatologist',
    'central atherosclerosis': 'General Physician',
    'central retinal artery or vein occlusion': 'Ophthalmologist',
    'cerebral edema': 'Neurologist',
    'cerebral palsy': 'Neurologist',
    'cervical cancer': 'Oncologist',
    'cervical disorder': 'General Physician',
    'cervicitis': 'Gynecologist / Obstetrician',
    'chalazion': 'Ophthalmologist',
    'chickenpox': 'Infectious Disease Specialist',
    'chlamydia': 'Infectious Disease Specialist',
    'cholecystitis': 'Gastroenterologist',
    'choledocholithiasis': 'Gastroenterologist',
    'cholesteatoma': 'ENT Specialist',
    'chondromalacia of the patella': 'General Physician',
    'chorioretinitis': 'General Physician',
    'chronic back pain': 'Orthopedic Specialist',
    'chronic constipation': 'Gastroenterologist',
    'chronic glaucoma': 'Ophthalmologist',
    'chronic inflammatory demyelinating polyneuropathy (cidp)': 'Neurologist',
    'chronic kidney disease': 'Nephrologist',
    'chronic knee pain': 'Orthopedic Specialist',
    'chronic obstructive pulmonary disease (copd)': 'Pulmonologist',
    'chronic otitis media': 'ENT Specialist',
    'chronic pain disorder': 'General Physician',
    'chronic pancreatitis': 'Gastroenterologist',
    'chronic rheumatic fever': 'General Physician',
    'chronic sinusitis': 'ENT Specialist',
    'cirrhosis': 'Gastroenterologist',
    'coagulation (bleeding) disorder': 'Hematologist',
    'cold sore': 'General Physician',
    'colonic polyp': 'Gastroenterologist',
    'colorectal cancer': 'Oncologist',
    'common cold': 'General Physician',
    'complex regional pain syndrome': 'General Physician',
    'concussion': 'General Physician',
    'conduct disorder': 'Psychiatrist',
    'conductive hearing loss': 'ENT Specialist',
    'congenital heart defect': 'Cardiologist',
    'congenital malformation syndrome': 'General Physician',
    'conjunctivitis': 'Ophthalmologist',
    'conjunctivitis due to allergy': 'Ophthalmologist',
    'conjunctivitis due to bacteria': 'Ophthalmologist',
    'conjunctivitis due to virus': 'Ophthalmologist',
    'contact dermatitis': 'Dermatologist',
    'conversion disorder': 'Psychiatrist',
    'cornea infection': 'Ophthalmologist',
    'corneal abrasion': 'Ophthalmologist',
    'corneal disorder': 'Ophthalmologist',
    'coronary atherosclerosis': 'Cardiologist',
    'cranial nerve palsy': 'Neurologist',
    'crohn disease': 'Gastroenterologist',
    'croup': 'ENT Specialist',
    'crushing injury': 'General Surgeon',
    'cushing syndrome': 'Endocrinologist',
    'cyst of the eyelid': 'Ophthalmologist',
    'cystic fibrosis': 'Pulmonologist',
    'cysticercosis': 'General Physician',
    'cystitis': 'General Physician',
    'de quervain disease': 'General Physician',
    'decubitus ulcer': 'General Surgeon',
    'deep vein thrombosis (dvt)': 'General Physician',
    'degenerative disc disease': 'Orthopedic Specialist',
    'delirium': 'General Physician',
    'dementia': 'Neurologist',
    'dental caries': 'Dentist / Oral & Maxillofacial Specialist',
    'depression': 'Psychiatrist',
    'dermatitis due to sun exposure': 'Dermatologist',
    'developmental disability': 'General Physician',
    'deviated nasal septum': 'ENT Specialist',
    'diabetes insipidus': 'Endocrinologist',
    'diabetic ketoacidosis': 'General Physician',
    'diabetic peripheral neuropathy': 'Neurologist',
    'diabetic retinopathy': 'Ophthalmologist',
    'diaper rash': 'General Physician',
    'dislocation of the ankle': 'Orthopedic Specialist',
    'dislocation of the elbow': 'Orthopedic Specialist',
    'dislocation of the finger': 'Orthopedic Specialist',
    'dislocation of the foot': 'Orthopedic Specialist',
    'dislocation of the hip': 'Orthopedic Specialist',
    'dislocation of the shoulder': 'Orthopedic Specialist',
    'dislocation of the vertebra': 'Orthopedic Specialist',
    'dislocation of the wrist': 'Orthopedic Specialist',
    'dissociative disorder': 'Psychiatrist',
    'diverticulitis': 'Gastroenterologist',
    'diverticulosis': 'Gastroenterologist',
    'down syndrome': 'General Physician',
    'drug abuse': 'Psychiatrist',
    'drug abuse (barbiturates)': 'Psychiatrist',
    'drug abuse (cocaine)': 'Psychiatrist',
    'drug abuse (methamphetamine)': 'Psychiatrist',
    'drug abuse (opioids)': 'Psychiatrist',
    'drug poisoning due to medication': 'General Physician',
    'drug reaction': 'General Physician',
    'drug withdrawal': 'Psychiatrist',
    'dry eye of unknown cause': 'Ophthalmologist',
    'dyshidrosis': 'Dermatologist',
    'dysthymic disorder': 'Psychiatrist',
    'ear drum damage': 'ENT Specialist',
    'ear wax impaction': 'ENT Specialist',
    'eating disorder': 'Psychiatrist',
    'ectopic pregnancy': 'Gynecologist / Obstetrician',
    'ectropion': 'General Physician',
    'eczema': 'Dermatologist',
    'edward syndrome': 'General Physician',
    'emphysema': 'Pulmonologist',
    'empyema': 'General Physician',
    'encephalitis': 'Infectious Disease Specialist',
    'endocarditis': 'Cardiologist',
    'endometrial cancer': 'Oncologist',
    'endometrial hyperplasia': 'Gynecologist / Obstetrician',
    'endometriosis': 'Gynecologist / Obstetrician',
    'endophthalmitis': 'Ophthalmologist',
    'envenomation from spider or animal bite': 'Dermatologist',
    'ependymoma': 'Neurologist',
    'epididymitis': 'Urologist',
    'epidural hemorrhage': 'Neurologist',
    'epilepsy': 'Neurologist',
    'erectile dysfunction': 'Urologist',
    'erythema multiforme': 'Dermatologist',
    'esophageal cancer': 'Oncologist',
    'esophagitis': 'Gastroenterologist',
    'essential tremor': 'Neurologist',
    'eustachian tube dysfunction (ear disorder)': 'ENT Specialist',
    'extrapyramidal effect of drugs': 'General Physician',
    'eye alignment disorder': 'Ophthalmologist',
    'factitious disorder': 'Psychiatrist',
    'female genitalia infection': 'Gynecologist / Obstetrician',
    'female infertility of unknown cause': 'Gynecologist / Obstetrician',
    'fetal alcohol syndrome': 'General Physician',
    'fibroadenoma': 'Gynecologist / Obstetrician',
    'fibrocystic breast disease': 'Gynecologist / Obstetrician',
    'fibromyalgia': 'General Physician',
    'flat feet': 'Orthopedic Specialist',
    'floaters': 'Ophthalmologist',
    'flu': 'General Physician',
    'fluid overload': 'General Physician',
    'folate deficiency': 'Hematologist',
    'food allergy': 'Allergist / Immunologist',
    'foreign body in the ear': 'ENT Specialist',
    'foreign body in the eye': 'Ophthalmologist',
    'foreign body in the gastrointestinal tract': 'Gastroenterologist',
    'foreign body in the throat': 'ENT Specialist',
    'foreign body in the vagina': 'General Surgeon',
    'fracture of the ankle': 'Orthopedic Specialist',
    'fracture of the arm': 'Orthopedic Specialist',
    'fracture of the facial bones': 'Orthopedic Specialist',
    'fracture of the finger': 'Orthopedic Specialist',
    'fracture of the foot': 'Orthopedic Specialist',
    'fracture of the hand': 'Orthopedic Specialist',
    'fracture of the jaw': 'Dentist / Oral & Maxillofacial Specialist',
    'fracture of the leg': 'Orthopedic Specialist',
    'fracture of the neck': 'Orthopedic Specialist',
    'fracture of the patella': 'Orthopedic Specialist',
    'fracture of the pelvis': 'Orthopedic Specialist',
    'fracture of the rib': 'Orthopedic Specialist',
    'fracture of the shoulder': 'Orthopedic Specialist',
    'fracture of the skull': 'Orthopedic Specialist',
    'fracture of the vertebra': 'Orthopedic Specialist',
    'frostbite': 'Dermatologist',
    'fungal infection of the hair': 'General Physician',
    'fungal infection of the skin': 'Dermatologist',
    'galactorrhea of unknown cause': 'Gynecologist / Obstetrician',
    'gallstone': 'Gastroenterologist',
    'ganglion cyst': 'General Physician',
    'gastritis': 'General Physician',
    'gastroduodenal ulcer': 'Gastroenterologist',
    'gastroesophageal reflux disease (gerd)': 'Gastroenterologist',
    'gastrointestinal hemorrhage': 'Gastroenterologist',
    'gastroparesis': 'Gastroenterologist',
    'genital herpes': 'Infectious Disease Specialist',
    'gestational diabetes': 'Endocrinologist',
    'glaucoma': 'Ophthalmologist',
    'glucocorticoid deficiency': 'Endocrinologist',
    'goiter': 'Endocrinologist',
    'gonorrhea': 'Infectious Disease Specialist',
    'gout': 'General Physician',
    'granuloma inguinale': 'General Physician',
    'graves disease': 'Endocrinologist',
    'guillain barre syndrome': 'Neurologist',
    'gum disease': 'Dentist / Oral & Maxillofacial Specialist',
    'gynecomastia': 'General Physician',
    'hammer toe': 'Orthopedic Specialist',
    'head and neck cancer': 'Oncologist',
    'head injury': 'General Surgeon',
    'headache after lumbar puncture': 'General Physician',
    'heart attack': 'Cardiologist',
    'heart block': 'Cardiologist',
    'heart contusion': 'Cardiologist',
    'heart failure': 'Cardiologist',
    'heat exhaustion': 'General Physician',
    'hemangioma': 'Dermatologist',
    'hemarthrosis': 'General Surgeon',
    'hematoma': 'General Surgeon',
    'hemiplegia': 'Neurologist',
    'hemolytic anemia': 'Hematologist',
    'hemophilia': 'Hematologist',
    'hemorrhoids': 'Gastroenterologist',
    'hepatic encephalopathy': 'Gastroenterologist',
    'hepatitis due to a toxin': 'Gastroenterologist',
    'herniated disk': 'General Surgeon',
    'herpangina': 'Cardiologist',
    'hiatal hernia': 'General Surgeon',
    'hidradenitis suppurativa': 'Dermatologist',
    'hirschsprung disease': 'General Physician',
    'hirsutism': 'Dermatologist',
    'hormone disorder': 'Endocrinologist',
    'hpv': 'Infectious Disease Specialist',
    'hydatidiform mole': 'Gynecologist / Obstetrician',
    'hydrocele of the testicle': 'Urologist',
    'hydrocephalus': 'Neurologist',
    'hydronephrosis': 'Nephrologist',
    'hypercalcemia': 'Endocrinologist',
    'hypercholesterolemia': 'General Physician',
    'hyperemesis gravidarum': 'General Physician',
    'hyperhidrosis': 'Dermatologist',
    'hyperkalemia': 'Endocrinologist',
    'hypernatremia': 'Endocrinologist',
    'hyperopia': 'General Physician',
    'hypertension of pregnancy': 'Gynecologist / Obstetrician',
    'hypertensive heart disease': 'Cardiologist',
    'hypertrophic obstructive cardiomyopathy (hocm)': 'Cardiologist',
    'hypocalcemia': 'Endocrinologist',
    'hypoglycemia': 'Endocrinologist',
    'hypokalemia': 'Endocrinologist',
    'hyponatremia': 'Endocrinologist',
    'hypothermia': 'General Physician',
    'hypothyroidism': 'Endocrinologist',
    'hypovolemia': 'General Physician',
    'idiopathic absence of menstruation': 'Gynecologist / Obstetrician',
    'idiopathic excessive menstruation': 'Gynecologist / Obstetrician',
    'idiopathic infrequent menstruation': 'Gynecologist / Obstetrician',
    'idiopathic irregular menstrual cycle': 'Gynecologist / Obstetrician',
    'idiopathic nonmenstrual bleeding': 'Gynecologist / Obstetrician',
    'idiopathic painful menstruation': 'Gynecologist / Obstetrician',
    'ileus': 'Gastroenterologist',
    'impetigo': 'Dermatologist',
    'impulse control disorder': 'Psychiatrist',
    'indigestion': 'General Physician',
    'induced abortion': 'Gynecologist / Obstetrician',
    'infection of open wound': 'General Surgeon',
    'infectious gastroenteritis': 'Gastroenterologist',
    'ingrown toe nail': 'General Physician',
    'inguinal hernia': 'General Surgeon',
    'injury of the ankle': 'General Surgeon',
    'injury to internal organ': 'General Surgeon',
    'injury to the abdomen': 'General Surgeon',
    'injury to the arm': 'General Surgeon',
    'injury to the face': 'General Surgeon',
    'injury to the finger': 'General Surgeon',
    'injury to the hand': 'General Surgeon',
    'injury to the hip': 'Orthopedic Specialist',
    'injury to the knee': 'General Surgeon',
    'injury to the leg': 'General Surgeon',
    'injury to the shoulder': 'Orthopedic Specialist',
    'injury to the spinal cord': 'Orthopedic Specialist',
    'injury to the trunk': 'General Surgeon',
    'insect bite': 'Dermatologist',
    'interstitial lung disease': 'Pulmonologist',
    'intertrigo (skin condition)': 'Dermatologist',
    'intestinal cancer': 'Oncologist',
    'intestinal disease': 'Gastroenterologist',
    'intestinal malabsorption': 'Gastroenterologist',
    'intestinal obstruction': 'Gastroenterologist',
    'intracerebral hemorrhage': 'Neurologist',
    'intracranial abscess': 'General Surgeon',
    'intracranial hemorrhage': 'Neurologist',
    'iridocyclitis': 'Ophthalmologist',
    'iron deficiency anemia': 'Hematologist',
    'irritable bowel syndrome': 'Gastroenterologist',
    'ischemia of the bowel': 'Gastroenterologist',
    'ischemic heart disease': 'Cardiologist',
    'itching of unknown cause': 'General Physician',
    'jaw disorder': 'Dentist / Oral & Maxillofacial Specialist',
    'joint effusion': 'Orthopedic Specialist',
    'juvenile rheumatoid arthritis': 'Orthopedic Specialist',
    'kidney cancer': 'Oncologist',
    'kidney disease due to longstanding hypertension': 'Nephrologist',
    'kidney failure': 'Nephrologist',
    'kidney stone': 'Urologist',
    'knee ligament or meniscus tear': 'ENT Specialist',
    'labyrinthitis': 'ENT Specialist',
    'lactose intolerance': 'General Physician',
    'laryngitis': 'ENT Specialist',
    'lateral epicondylitis (tennis elbow)': 'Orthopedic Specialist',
    'leukemia': 'Oncologist',
    'lewy body dementia': 'Neurologist',
    'lice': 'General Physician',
    'lichen simplex': 'Dermatologist',
    'lipoma': 'Dermatologist',
    'liver cancer': 'Oncologist',
    'liver disease': 'Gastroenterologist',
    'lumbago': 'Orthopedic Specialist',
    'lung cancer': 'Oncologist',
    'lung contusion': 'Pulmonologist',
    'lyme disease': 'Infectious Disease Specialist',
    'lymphadenitis': 'General Physician',
    'lymphedema': 'General Physician',
    'lymphogranuloma venereum': 'General Physician',
    'lymphoma': 'Oncologist',
    'macular degeneration': 'Ophthalmologist',
    'magnesium deficiency': 'General Physician',
    'malaria': 'Infectious Disease Specialist',
    'male genitalia infection': 'General Physician',
    'malignant hypertension': 'General Physician',
    'marijuana abuse': 'General Physician',
    'mastectomy': 'General Surgeon',
    'mastoiditis': 'ENT Specialist',
    'melanoma': 'Oncologist',
    'meniere disease': 'ENT Specialist',
    'meningioma': 'Neurologist',
    'meningitis': 'Infectious Disease Specialist',
    'menopause': 'Gynecologist / Obstetrician',
    'metabolic disorder': 'Endocrinologist',
    'metastatic cancer': 'Oncologist',
    'migraine': 'Neurologist',
    'missed abortion': 'Gynecologist / Obstetrician',
    'mitral valve disease': 'Cardiologist',
    'mittelschmerz': 'Gynecologist / Obstetrician',
    'molluscum contagiosum': 'Dermatologist',
    'mononeuritis': 'Neurologist',
    'mononucleosis': 'Infectious Disease Specialist',
    'moyamoya disease': 'Neurologist',
    'mucositis': 'General Physician',
    'multiple myeloma': 'Oncologist',
    'multiple sclerosis': 'Neurologist',
    'mumps': 'Infectious Disease Specialist',
    'muscle spasm': 'Orthopedic Specialist',
    'muscular dystrophy': 'Orthopedic Specialist',
    'myasthenia gravis': 'Neurologist',
    'myoclonus': 'Neurologist',
    'myopia': 'General Physician',
    'myositis': 'Orthopedic Specialist',
    'narcolepsy': 'Neurologist',
    'nasal polyp': 'ENT Specialist',
    'neonatal jaundice': 'General Physician',
    'nerve impingement near the shoulder': 'ENT Specialist',
    'neuralgia': 'Neurologist',
    'neurofibromatosis': 'Neurologist',
    'neuropathy due to drugs': 'Neurologist',
    'neurosis': 'Psychiatrist',
    'nonalcoholic liver disease (nash)': 'Gastroenterologist',
    'noninfectious gastroenteritis': 'Gastroenterologist',
    'normal pressure hydrocephalus': 'Neurologist',
    'nose disorder': 'ENT Specialist',
    'obsessive compulsive disorder (ocd)': 'Psychiatrist',
    'obstructive sleep apnea (osa)': 'General Physician',
    'onychomycosis': 'Dermatologist',
    'open wound from surgical incision': 'General Surgeon',
    'open wound of the arm': 'General Surgeon',
    'open wound of the back': 'General Surgeon',
    'open wound of the ear': 'ENT Specialist',
    'open wound of the eye': 'Ophthalmologist',
    'open wound of the foot': 'General Surgeon',
    'open wound of the lip': 'General Surgeon',
    'open wound of the mouth': 'Dentist / Oral & Maxillofacial Specialist',
    'open wound of the neck': 'General Surgeon',
    'open wound of the nose': 'ENT Specialist',
    'oppositional disorder': 'General Physician',
    'optic neuritis': 'Neurologist',
    'oral mucosal lesion': 'Dentist / Oral & Maxillofacial Specialist',
    'oral thrush (yeast infection)': 'Dentist / Oral & Maxillofacial Specialist',
    'orbital cellulitis': 'Dermatologist',
    'orthostatic hypotension': 'General Physician',
    'osteoarthritis': 'Orthopedic Specialist',
    'osteochondroma': 'Orthopedic Specialist',
    'osteochondrosis': 'Orthopedic Specialist',
    'osteomyelitis': 'Orthopedic Specialist',
    'osteoporosis': 'Orthopedic Specialist',
    "otitis externa (swimmer's ear)": 'ENT Specialist',
    'otitis media': 'ENT Specialist',
    'otosclerosis': 'ENT Specialist',
    'ovarian cancer': 'Oncologist',
    'ovarian cyst': 'Gynecologist / Obstetrician',
    'ovarian torsion': 'Gynecologist / Obstetrician',
    'overflow incontinence': 'Urologist',
    'pain after an operation': 'General Physician',
    'pain disorder affecting the neck': 'General Physician',
    'pancreatic cancer': 'Oncologist',
    'panic attack': 'Psychiatrist',
    'panic disorder': 'Psychiatrist',
    'parasitic disease': 'Infectious Disease Specialist',
    'parathyroid adenoma': 'Endocrinologist',
    'parkinson disease': 'Neurologist',
    'paronychia': 'Dermatologist',
    'paroxysmal supraventricular tachycardia': 'Cardiologist',
    'paroxysmal ventricular tachycardia': 'Cardiologist',
    'pelvic inflammatory disease': 'General Physician',
    'pelvic organ prolapse': 'General Physician',
    'pemphigus': 'Dermatologist',
    'pericarditis': 'Cardiologist',
    'peripheral arterial disease': 'General Physician',
    'peripheral arterial embolism': 'General Physician',
    'peripheral nerve disorder': 'General Physician',
    'perirectal infection': 'Gastroenterologist',
    'peritonitis': 'Gastroenterologist',
    'peritonsillar abscess': 'ENT Specialist',
    'persistent vomiting of unknown cause': 'General Physician',
    'personality disorder': 'Psychiatrist',
    'peyronie disease': 'Urologist',
    'pharyngitis': 'ENT Specialist',
    'phimosis': 'Urologist',
    'pilonidal cyst': 'General Physician',
    'pinguecula': 'Ophthalmologist',
    'pinworm infection': 'General Physician',
    'pituitary adenoma': 'Endocrinologist',
    'pituitary disorder': 'Endocrinologist',
    'pityriasis rosea': 'Dermatologist',
    'placenta previa': 'Gynecologist / Obstetrician',
    'placental abruption': 'Gynecologist / Obstetrician',
    'plantar fasciitis': 'Orthopedic Specialist',
    'pleural effusion': 'Pulmonologist',
    'pneumoconiosis': 'Pulmonologist',
    'pneumonia': 'Pulmonologist',
    'pneumothorax': 'Pulmonologist',
    'poisoning due to analgesics': 'General Physician',
    'poisoning due to anticonvulsants': 'General Physician',
    'poisoning due to antidepressants': 'General Physician',
    'poisoning due to antihypertensives': 'General Physician',
    'poisoning due to antimicrobial drugs': 'General Physician',
    'poisoning due to antipsychotics': 'Psychiatrist',
    'poisoning due to ethylene glycol': 'General Physician',
    'poisoning due to gas': 'General Physician',
    'poisoning due to opioids': 'General Physician',
    'poisoning due to sedatives': 'General Physician',
    'polycystic kidney disease': 'Nephrologist',
    'polycystic ovarian syndrome (pcos)': 'Gynecologist / Obstetrician',
    'polycythemia vera': 'Hematologist',
    'polymyalgia rheumatica': 'Orthopedic Specialist',
    'post-traumatic stress disorder (ptsd)': 'Psychiatrist',
    'postoperative infection': 'General Surgeon',
    'postpartum depression': 'Gynecologist / Obstetrician',
    'preeclampsia': 'Gynecologist / Obstetrician',
    'pregnancy': 'Gynecologist / Obstetrician',
    'premature atrial contractions (pacs)': 'Cardiologist',
    'premature ovarian failure': 'Gynecologist / Obstetrician',
    'premature rupture of amniotic membrane': 'Gynecologist / Obstetrician',
    'premature ventricular contractions (pvcs)': 'Cardiologist',
    'premenstrual tension syndrome': 'Gynecologist / Obstetrician',
    'presbyacusis': 'ENT Specialist',
    'presbyopia': 'General Physician',
    'priapism': 'Urologist',
    'primary immunodeficiency': 'Infectious Disease Specialist',
    'primary insomnia': 'General Physician',
    'primary kidney disease': 'Nephrologist',
    'problem during pregnancy': 'Gynecologist / Obstetrician',
    'prostate cancer': 'Oncologist',
    'prostatitis': 'Urologist',
    'protein deficiency': 'General Physician',
    'pseudohypoparathyroidism': 'Endocrinologist',
    'pseudotumor cerebri': 'Neurologist',
    'psoriasis': 'Dermatologist',
    'psychosexual disorder': 'Psychiatrist',
    'psychotic disorder': 'Psychiatrist',
    'pterygium': 'Ophthalmologist',
    'pulmonary congestion': 'Pulmonologist',
    'pulmonary embolism': 'Pulmonologist',
    'pulmonary eosinophilia': 'Pulmonologist',
    'pulmonary fibrosis': 'Pulmonologist',
    'pulmonary hypertension': 'Pulmonologist',
    'pyelonephritis': 'General Physician',
    'pyloric stenosis': 'General Physician',
    'pyogenic skin infection': 'Dermatologist',
    'raynaud disease': 'General Physician',
    'rectal disorder': 'Gastroenterologist',
    'restless leg syndrome': 'General Physician',
    'retinal detachment': 'Ophthalmologist',
    'retinopathy due to high blood pressure': 'Ophthalmologist',
    'rhabdomyolysis': 'Orthopedic Specialist',
    'rheumatoid arthritis': 'Orthopedic Specialist',
    'rosacea': 'Dermatologist',
    'rotator cuff injury': 'Orthopedic Specialist',
    'salivary gland disorder': 'Dentist / Oral & Maxillofacial Specialist',
    'sarcoidosis': 'Pulmonologist',
    'scabies': 'Dermatologist',
    'scar': 'Dermatologist',
    'scarlet fever': 'Dermatologist',
    'schizophrenia': 'Psychiatrist',
    'sciatica': 'Orthopedic Specialist',
    'scleritis': 'Ophthalmologist',
    'scleroderma': 'General Physician',
    'scoliosis': 'Orthopedic Specialist',
    'seasonal allergies (hay fever)': 'Allergist / Immunologist',
    'sebaceous cyst': 'Dermatologist',
    'seborrheic dermatitis': 'Dermatologist',
    'seborrheic keratosis': 'Dermatologist',
    'sensorineural hearing loss': 'ENT Specialist',
    'sepsis': 'Infectious Disease Specialist',
    'septic arthritis': 'Orthopedic Specialist',
    'shingles (herpes zoster)': 'Dermatologist',
    'sialoadenitis': 'General Physician',
    'sick sinus syndrome': 'Cardiologist',
    'sickle cell anemia': 'Hematologist',
    'sickle cell crisis': 'Hematologist',
    'sinus bradycardia': 'Cardiologist',
    'sjogren syndrome': 'General Physician',
    'skin cancer': 'Oncologist',
    'skin disorder': 'Dermatologist',
    'skin pigmentation disorder': 'Dermatologist',
    'skin polyp': 'Dermatologist',
    'smoking or tobacco addiction': 'Psychiatrist',
    'social phobia': 'Psychiatrist',
    'soft tissue sarcoma': 'Oncologist',
    'somatization disorder': 'Psychiatrist',
    'spermatocele': 'Urologist',
    'spina bifida': 'General Physician',
    'spinal stenosis': 'Orthopedic Specialist',
    'spinocerebellar ataxia': 'Neurologist',
    'spondylitis': 'Orthopedic Specialist',
    'spondylolisthesis': 'Orthopedic Specialist',
    'spondylosis': 'Orthopedic Specialist',
    'spontaneous abortion': 'Gynecologist / Obstetrician',
    'sprain or strain': 'Orthopedic Specialist',
    'stenosis of the tear duct': 'ENT Specialist',
    'stomach cancer': 'Oncologist',
    'strep throat': 'Infectious Disease Specialist',
    'stress incontinence': 'Urologist',
    'stricture of the esophagus': 'Gastroenterologist',
    'stroke': 'Neurologist',
    'stye': 'Ophthalmologist',
    'subacute thyroiditis': 'Endocrinologist',
    'subarachnoid hemorrhage': 'Neurologist',
    'subconjunctival hemorrhage': 'General Physician',
    'subdural hemorrhage': 'Neurologist',
    'substance-related mental disorder': 'Psychiatrist',
    'syphilis': 'Infectious Disease Specialist',
    'syringomyelia': 'Neurologist',
    'systemic lupus erythematosis (sle)': 'General Physician',
    'teething syndrome': 'General Physician',
    'temporary or benign blood in urine': 'General Physician',
    'temporomandibular joint disorder': 'Orthopedic Specialist',
    'tendinitis': 'Orthopedic Specialist',
    'tension headache': 'General Physician',
    'testicular cancer': 'Oncologist',
    'testicular disorder': 'Urologist',
    'testicular torsion': 'Urologist',
    'thoracic aortic aneurysm': 'Cardiologist',
    'thoracic outlet syndrome': 'General Physician',
    'threatened pregnancy': 'Gynecologist / Obstetrician',
    'thrombocytopenia': 'Hematologist',
    'thrombophlebitis': 'Hematologist',
    'thyroid cancer': 'Oncologist',
    'thyroid disease': 'Endocrinologist',
    'thyroid nodule': 'Endocrinologist',
    'tic (movement) disorder': 'General Physician',
    'tietze syndrome': 'Orthopedic Specialist',
    'tinnitus of unknown cause': 'ENT Specialist',
    'tonsillar hypertrophy': 'ENT Specialist',
    'tonsillitis': 'ENT Specialist',
    'tooth abscess': 'Dentist / Oral & Maxillofacial Specialist',
    'tooth disorder': 'Dentist / Oral & Maxillofacial Specialist',
    'torticollis': 'Orthopedic Specialist',
    'tourette syndrome': 'General Physician',
    'toxic multinodular goiter': 'Endocrinologist',
    'toxoplasmosis': 'Infectious Disease Specialist',
    'tracheitis': 'ENT Specialist',
    'transient ischemic attack': 'Neurologist',
    'trichiasis': 'Ophthalmologist',
    'trichomonas infection': 'Infectious Disease Specialist',
    'trigeminal neuralgia': 'Neurologist',
    'trigger finger (finger disorder)': 'Orthopedic Specialist',
    'tuberculosis': 'Pulmonologist',
    'tuberous sclerosis': 'General Physician',
    'ulcerative colitis': 'Gastroenterologist',
    'urethral disorder': 'Urologist',
    'urethral stricture': 'Urologist',
    'urethral valves': 'Urologist',
    'urethritis': 'General Physician',
    'urge incontinence': 'Urologist',
    'urinary tract infection': 'Urologist',
    'urinary tract obstruction': 'Urologist',
    'uterine atony': 'Gynecologist / Obstetrician',
    'uterine fibroids': 'Gynecologist / Obstetrician',
    'uveitis': 'Ophthalmologist',
    'vaginal cyst': 'Gynecologist / Obstetrician',
    'vaginal yeast infection': 'Gynecologist / Obstetrician',
    'vaginismus': 'Gynecologist / Obstetrician',
    'vaginitis': 'Gynecologist / Obstetrician',
    'valley fever': 'Pulmonologist',
    'varicocele of the testicles': 'Urologist',
    'varicose veins': 'General Physician',
    'vasculitis': 'General Physician',
    'venous insufficiency': 'General Physician',
    'vertebrobasilar insufficiency': 'Neurologist',
    'vesicoureteral reflux': 'Urologist',
    'viral exanthem': 'Dermatologist',
    'viral hepatitis': 'Gastroenterologist',
    'viral warts': 'Dermatologist',
    'vitamin b12 deficiency': 'Hematologist',
    'vitamin d deficiency': 'General Physician',
    'vitreous degeneration': 'Ophthalmologist',
    'vitreous hemorrhage': 'Ophthalmologist',
    'vocal cord polyp': 'ENT Specialist',
    'volvulus': 'Gastroenterologist',
    'vulvar cancer': 'Oncologist',
    'vulvar disorder': 'Gynecologist / Obstetrician',
    'vulvodynia': 'General Physician',
    'wernicke korsakoff syndrome': 'General Physician',
    'white blood cell disease': 'Hematologist',
    'whooping cough': 'Pulmonologist',
    'wilson disease': 'General Physician',
    'yeast infection': 'Infectious Disease Specialist',
    'zenker diverticulum': 'Gastroenterologist',
}


def recommend_specialist(disease: str) -> str:
    """Return the recommended specialist for a predicted disease."""
    if not disease:
        return "General Physician"

    disease_clean = disease.strip().lower()
    for name, specialist in DISEASE_SPECIALIST.items():
        if name.lower() == disease_clean:
            return specialist

    return "General Physician"